### ISSUE TITLE
Final Capstone Kanban board review request

### ISSUE THREAD

**Issue by Felix45** [silviatofana/Doctor-appointment_backend#17]
## Kanban board review request
In this capstone group, we are a team of four people namely @silviatofana , @BasitKorede , @Theophileaseh and @Felix45 

## Kanban link
[Kanban board link >>](https://github.com/users/silviatofana/projects/6/views/1)

## Kanban board screenshots I

![Screenshot from 2022-10-19 18-02-17](https://user-images.githubusercontent.com/16392046/196729267-55d632f6-2314-4728-ae10-cf5a7667e5a1.png)

## Kanban board screenshot II

![Screenshot from 2022-10-19 18-05-28](https://user-images.githubusercontent.com/16392046/196729665-e986f2a6-c948-45c2-81e2-62da32c6b172.png)

**Comment by vichuge** [comment]
Hi dear student, 

Good job so far!
You still need to work on some issues to prepare your project for the final evaluation, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)


## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

- Just one aspect to improve, one of the cards doesn't have assigned points for the task. Please add it.
<img width="553" alt="image" src="https://user-images.githubusercontent.com/20563252/196734948-8c0d9f83-4cd3-4b0b-8d84-9e5685e3b2cd.png">


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by Meltrust** [comment]
Hi @Felix45,


## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 





Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
